### ISSUE TITLE
Recover items in shops

### ISSUE THREAD

**Issue by ssardina** [ssardina-agts/agtcity-server#1]
In the 2017 edition of the server, items could be bought in shops.

In the 2018 edition, that was removed and items can now be only obtained in resource nodes.

As items in shop was a good feature and helped getting a first system in a course, we would like to bring that feature (i.e., items in shops) back to the 2018 server. Shops will still remain the ability to buy upgrades of course.

**Comment by ayoung012** [comment]
In order to bring items back to shops, we look back to two commits that removed the functionality. Commits 761f14e5168822dac25b199bae55a03700c9accf and d01a3782dab91a5e38605356440cf2732b63bfdc sum up the removal of items in shops:

 * baseItems are now referred to as resources
 * Tools are removed from shops and the game entirely, replaced by roles that serve the same purpose, but agents are given roles upfront.

The changes in new branch `feature/items-in-shops` enable the purchase of base items (resources) in shops using the buy action.

Additionally, a unit test for the buy action has been re-added.

Testing the branch with `mvn test` shows the buy action working correctly, but has caused a 'quantity off by one error' for the resource nodes gather action unit test. Unsure what has caused it.

**Comment by ayoung012** [comment]
@ssardina I have resolved all unit test issues, and confirmed that items in shops are shown in the monitor UI.

However I am having trouble getting the full shop representation (with items) to come up in the Prolog KB dump. Got any pointers as to where I should be looking? 

Note there will also be issues with the java entity you have:

**Comment by ayoung012** [comment]
@ssardina I just remembered that our sarl client relies on the eismassim package within massim, and that the pom must be updated to get shop percept changes in this new version. I installed a local massim build and updated the pom, and all seems to working correctly.

Where/how should we host this altered massim_2018 package and what should the version be?

**Comment by ssardina** [comment]
ops! Just saw this @adam, sorry....

I am a bit lost, I can help you with Prolog stuff but I need a full README with all the new system that you build. 

What are the new components and where are all the systems? I guess we have:

* A new massime server (which is 2018 upgraded with shops)
* A new SARL MW that can talk to that server
* A new SARL core JAS system that uses the new MW
* A new eismassime package?

We should host everything in github under my name. Let me know where each piece is now. Where is the altered server for example? ohh dear I am catching up...

**Comment by ssardina** [comment]
I think this has been done and merged into master
